### ISSUE TITLE
Default instrument is awful

### ISSUE THREAD

**Issue by kometbomb** [kometbomb/klystrack#159]

**Comment by n00bstar** [comment]
I think it's super useful that the default instrument is so crappy actually. That way, when you're looking for a spot to create a new instrument, you have no risk to overwrite something useful that you are using somewhere in the song. It also forces new users to learn to edit instruments. It might set a steeper learning curve at first, but it's an easy one to overcome, and a satisfying one too.

**Comment by kometbomb** [comment]
That is a good point. The other option would be to make the default instrument silent (so you won't confuse it with useful stuff) but that would be even more hostile towards the newbies.
