### ISSUE TITLE
Default song should use standard step sizes

### ISSUE THREAD

**Issue by n00bstar** [kometbomb/klystrack#163]
The default length for pretty much every tracker ever is 64 rows. Right now the default song is set with patterns of 64 rows, but step length of 16. This is extremely confusing for new users. (Also since you added the pattern break command, I think there's no reason to keep this step length stuff anymore.. it breaks the sequencer's display more than anything else)

**Comment by iLKke** [comment]
Step is useful for when you have tracks of varying lengths.

If you don't need the functionality then just don't hange step from 64 and you're set, right?

**Comment by n00bstar** [comment]
The default (both the config, and the default.kt song) should still be something more standard. Having patterns of varying length is an exception more than the rule, so the default configuration should reflect this.

**Comment by iLKke** [comment]
Agree fully, it should be 64.

I was commenting on your remark in parentheses about removing the option to change the step altogether
