### ISSUE TITLE
Add names to waves

### ISSUE THREAD

**Issue by n00bstar** [kometbomb/klystrack#165]
Since instruments have names, and effects have name. Maybe it would be good to have names for the waves too? I know it would required moving crap around on the instrument page...again :) But it would make it easier to edit instruments instead of going "argh, which one is my sine wave again?" and go look through all the waves to find it.

**Comment by kometbomb** [comment]
Shouldn't need any extra space in the instrument editor if the name is visible on the status bar (the FX BUS parameter does this now). Then you can at least browse the samples instead of going by ear.
