### ISSUE TITLE
Cursor gets stuck in the sequence editor

### ISSUE THREAD

**Issue by n00bstar** [kometbomb/klystrack#170]
Finally found a 100% repro. It's a bit of a weird one:

1) Load a song and press play
2) Open two or more Chrome (or whatever else) windows
3) Place cursor in the sequence editor
4) Click on the stacked Chrome icons in the task bar to show the multiple available open windows
5) Click on the stacked Chrome icons again to close the previews
6) Return to Klystrack
7) Tap enter to move cursor from Seq to Patt.
8) Notice how it comes back to the Seq right away
9) Only way to rest this is pressing ESC and cancelling that pop up

**Comment by kometbomb** [comment]
Ok that is weird.

I noticed you can achieve the same by holding left mouse button down on the sequence editor pattern and trying to move the cursor (it will jump back). Might be related to how holding the mouse button triggers repeat.
