### ISSUE TITLE
Settings are not saved.

### ISSUE THREAD

**Issue by Gomme-** [kometbomb/klystrack#179]
I am on linux mint 17.1 Cinnamon 64-bits. I have installed the 1.6.1 version. When I change settings (for example : keymap, pixel size, and other things in "prefs"), they are not saved when I restart klystrack.

**Comment by kometbomb** [comment]
Looks like the tilde expansion is not working in 64-bit Linux. Perhaps that is not even needed.

**Comment by Gomme-** [comment]
Ok, is there anything I can do to help to correct that?

**Comment by kometbomb** [comment]
Probably not. For some reason, I can query the HOME enviroment variable
when loading the preferences file (~/.klystrack) but not when saving the
file. Also, happens only with the 64-bit build. Perhaps some code
overwrites the variables or something like that.

2015-04-20 19:50 GMT+03:00 Gomme- <notifications@github.com>:

**Comment by kometbomb** [comment]
I found an alternative way to get the needed directory that seems to work. Thanks for reminding me about this bug!

**Comment by Gomme-** [comment]
No problem, and thank you for all this work :)
By the way, I haven't tested the favorite folders option but I suppose it will give the same error as the file is ~/.klystrackfavorites. I can test that later if necessary.

**Comment by kometbomb** [comment]
Yeah, it should crash similarly.

**Comment by kometbomb** [comment]
Fixed by kometbomb/klystrack@42442cec47b8130660ac0d8b2461ec8cf3c33985
