### ISSUE TITLE
A better reverb editor

### ISSUE THREAD

**Issue by kometbomb** [kometbomb/klystrack#181]
- Better support for tick/step sync (will tap delays follow song speed parameters?)
- Visual display of taps (able to edit with mouse?)
- Better reverb wizard

**Comment by n00bstar** [comment]
Instead of having just the general "spread" feature for stereo delays. It would be cool if each tap could have it's own panning setting.

**Comment by n00bstar** [comment]
Also.. a on/off feature for each tap. Sometimes when you want to do more complex effects, you need to edit each tap separately to make sure they hit at the right time, and the only way to solo a tap is to put all others at -INF.. and then you have to manually set the volumes back for each tap again.

**Comment by kometbomb** [comment]
Good points. Backwards compatible stereo spread can of course done by doubling the taps and delaying the left side (that's how it works internally anyways).

**Comment by kometbomb** [comment]
Everything but automatic sync to tempo is now implemented.
