### ISSUE TITLE
Instrument program list does not render correctly.

### ISSUE THREAD

**Issue by chenz** [kometbomb/klystrack#182]
The instrument program list is cut off at the bottom:

![klystrack-1](https://cloud.githubusercontent.com/assets/7843/7444586/6c22c3dc-f18a-11e4-9d56-58e581206244.png)

With 2x2 pixels, it does not render at all:

![klystrack-2](https://cloud.githubusercontent.com/assets/7843/7444588/72af1142-f18a-11e4-8159-1271b7f3af27.png)

(tried with 1.6.1 (current master), 1.7 branch does not build for me atm).

**Comment by kometbomb** [comment]
Perhaps related to the clipping problem in SDL. Have you tried to disable rendering to texture (you can find it in the Prefs menu)?

**Comment by chenz** [comment]
Disabling render-to-texture fixed it. I found the related bug reports in SDL's Bugzilla, including your comment :)

**Comment by kometbomb** [comment]
Ok, good. :)
