### ISSUE TITLE
Switching between KT and WAV files messes up file extensions

### ISSUE THREAD

**Issue by n00bstar** [kometbomb/klystrack#195]
If you go back and forth between saving a song normally, or exporting a .wav, the file extension stays at whatever was saved first. Save a KT song, then export a .wav, and it will be named blabla.KT. Export a .wav first, and then save a KT song and the file will be named dickrub.wav

The file itself is still good, it's just the extension. Manually renaming the file afterwards works just fine.

**Comment by kometbomb** [comment]
So, it actually just used the song filename for both. Fixing it so it remembers the export *.wav filename separately.
