### ISSUE TITLE
Cannot build, dependencies unknown

### ISSUE THREAD

**Issue by natemccoy** [kometbomb/klystrack#205]
Seems like a few headers are missing on my system but I am not sure what libraries you are using. Do you have a list of dependencies?

Here are some of the missing header files, after running `make` from the root of the cloned git repo.

    #include "gfx/gfx.h"
    #include "gui/menu.h"
    #include "gui/shortcuts.h"
    #include "gui/view.h"
    #include "macros.h"
    #include "SDL.h"
    #include "SDL.h"
    #include "SDL_rwops.h"
    #include "snd/music.h"

**Comment by kometbomb** [comment]
Check this wiki article on how to build it: https://github.com/kometbomb/klystrack/wiki/HowToCompile

**Comment by natemccoy** [comment]
Just tried it out, I installed the correct libraries but it got this error.

    src/theme.c: In function ‘set_scaled_cursor’:
    src/theme.c:363:3: error: format not a string literal and no format arguments [-Werror=format-security]
       warning(SDL_GetError());
       ^
    cc1: all warnings being treated as errors

Why dont you add that link to a `README.md` file in the main repository with a basic description?

**Comment by kometbomb** [comment]
Fixed that warning.

I was going to put that info on the main homepage but I guess it's good to have it in the readme as well.

**Comment by natemccoy** [comment]
I am getting other errors, but they are not related to this problem anymore. I will close this issue
