### ISSUE TITLE
Crash when cutting over start of a pattern (or exactly at edge)

### ISSUE THREAD

**Issue by bryc** [kometbomb/klystrack#208]
![image](https://cloud.githubusercontent.com/assets/1408749/22936951/03d565f0-f2a5-11e6-8445-8732ac929684.png)
![image](https://cloud.githubusercontent.com/assets/1408749/22937304/3537e036-f2a6-11e6-946c-59974aa6ba8b.png)

Crashed earlier and was able to reproduce it each time:

1) Move a pattern a few steps ahead so some empty data is before it
2) Hold shift and select some rows adjacent to it, then press CTRL + X
3) Crash

**Comment by kometbomb** [comment]
It seems pasting data outside a pattern also crashes.
