### ISSUE TITLE
Crash when song begins a new loop

### ISSUE THREAD

**Issue by Badope6** [kometbomb/klystrack#211]
I haven't tested this a lot, but when playing back this file (put it in a zip file)
[BotB 25394 shinichi - reasoneater.zip](https://github.com/kometbomb/klystrack/files/946808/BotB.25394.shinichi.-.reasoneater.zip)
, when klystrack goes back to the start and replays/loops it crashes the program.

It also results in resetting all preferences somehow when reopening klystrack.

**Comment by kometbomb** [comment]
Can definitely reproduce the crash with this file. Thanks!

**Comment by kometbomb** [comment]
The cause of the trouble was the wavetable reading outside the sample area. Might fix some other random crashes as well.

**Comment by kometbomb** [comment]
It would be super nice if you could test if the song crashes. Here's a fix: [klystrack-1.7.1-win32.zip](https://github.com/kometbomb/klystrack/files/966715/klystrack-1.7.1-win32.zip)

I ran it through Valgrind and did not get the error and on my Windows machine it doesn't crash anymore but you never know with these things.

**Comment by Badope6** [comment]
Yep, seems to be fixed. Sorry for the late reply, unfortunately didn't get properly notified by GitHub.

**Comment by kometbomb** [comment]
NP, better late than never! Thanks for confirming. :)
