### ISSUE TITLE
Making a new song doesn't reset pattern lengths

### ISSUE THREAD

**Issue by FreeFull** [kometbomb/klystrack#213]
To reproduce:
* Open an existing song, for example "Ocean Loader III.kt" from the example songs.
* Clear everything with "Ctrl-n" or "New song" from the File menu
* Any patterns you add in the pattern editor will have the same length that they had in the previous song

This means that to get a clean state, you currently have to close klystrack and open a new instance of it. "Zap sequence" doesn't do anything to the pattern lengths either.

**Comment by kometbomb** [comment]
Do you have the "Same as STEP" option checked in prefs?

**Comment by FreeFull** [comment]
I do have that option checked.

**Comment by FreeFull** [comment]
It seems the commit with the fix got reverted. Should the issue be reopened?

**Comment by kometbomb** [comment]
I reverted it but also recommitted later. See 2a2cbaf913e98.

But maybe you are still getting the wrong behavior... could you please check with the latest build (1.7.3)?

**Comment by FreeFull** [comment]
The problem has been fixed by 2a2cbaf.
