### ISSUE TITLE
Klystrack License?

### ISSUE THREAD

**Issue by kphillisjr** [kometbomb/klystrack#214]
I was wondering, What is the license of this source repository? To my knowledge from the small portions I can find this project is currently licensed under the MIT License.

**Comment by kometbomb** [comment]
Yes, it's MIT (both code and assets) and also the Mersenne Twister has its own license. I think it should explicitly say all this somewhere but maybe it was lost at some point.

Basically, as long as you don't claim anything as your own, everything goes.

**Comment by kphillisjr** [comment]
That is good to know, but do you happen to know where the Mersene Twister source code is located at?

**Comment by kometbomb** [comment]
Klystrack uses klystron which has the RNG code: https://github.com/kometbomb/klystron/blob/master/src/util/rnd.c
