### ISSUE TITLE
[OSX] Trouble loading theme at '~/res/Default'

### ISSUE THREAD

**Issue by nathanhornby** [kometbomb/klystrack#217]
Brand new to klystrack so sorry if this is obvious, but on the new OSX (http://plugins.ro/klystrack) build I'm getting the following error along with a crash when attempting to run the app from the terminal:

> [DEBUG] Loading theme '/Users/nathanhornby/res/Default'
> [WARNING] Can't open bundle '/Users/nathanhornby/res/Default'
> [WARNING] Theme loading failed
> [FATAL] Default theme at '/Users/nathanhornby/res/Default' could not be loaded, klystrack will now (most likely) crash

**Comment by nathanhornby** [comment]
Turns out the 'res' folder is bundled in the zip, so just needs moving to the users home folder. Would be helpful to mention on install instructions on the download page (at http://plugins.ro/klystrack that is).

**Comment by TBD** [comment]
added to the download page to start from command line in the directory where klystrack binary is.
thanks @nathanhornby
