### ISSUE TITLE
Crashes if path contains non-ascii chars

### ISSUE THREAD

**Issue by dmi7ry** [kometbomb/klystrack#218]
If path where I placed klystrack contains Cyrillic (I think any other non-ascii chars too), it crashes when I try to start it.

Windows 7 x 64.

**Comment by kometbomb** [comment]
I am replacing the routine with SDL_GetBasePath() that should work cross-platform (not sure why I'm not using it already, maybe because it's SDL 2.0 stuff etc.). This seems to fix it.
