### ISSUE TITLE
Embed in-program command list.

### ISSUE THREAD

**Issue by darkhog** [kometbomb/klystrack#220]
Maybe under menu->info->commands? Much more useful than looking constantly at the wiki (and risk productivity loss from the likes of TVTropes, Facebook and so on).

**Comment by kometbomb** [comment]
Hit F1.

2017-12-15 7:21 GMT+02:00 darkhog <notifications@github.com>:

**Comment by darkhog** [comment]
Thanks. I think it still should be in menu as well since I'm usually running an autohotkey script that turns few of the F* keys into media keys (since my keyboard doesn't have these). Additionally, many laptops have "real" function keys being under Fn+F* key while things like brightness up/down and so on taking a precedence. Sometimes is just more convenient to click a menu item.

**Comment by kometbomb** [comment]
That's a fair point. I will add that.

2017-12-15 20:38 GMT+02:00 darkhog <notifications@github.com>:

**Comment by kometbomb** [comment]
Added by 5d23350567f5da641a9e7903843093144893f1a7
