### ISSUE TITLE
failed to build on 32bit powerpc

### ISSUE THREAD

**Issue by alexmyczko** [kometbomb/klystrack#222]
```
Compiling config.c...
In file included from ../klystron/src/gfx/objhdr.h:32:0,
                 from ../klystron/src/gfx/bgcell.h:30,
                 from ../klystron/src/gfx/tiledescriptor.h:31,
                 from ../klystron/src/gfx/font.h:30,
                 from src/mused.h:30,
                 from src/config.c:27:
src/config.c: In function ‘apply_config’:
../klystron/src/macros.h:91:26: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
 #  define CASTTOPTR(t,x) (t*)(Uint64)x
                          ^
src/config.c:87:21: note: in expansion of macro ‘CASTTOPTR’
  change_pixel_scale(CASTTOPTR(void,mused.pixel_scale), 0, 0);
                     ^
../klystron/src/macros.h:91:26: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
 #  define CASTTOPTR(t,x) (t*)(Uint64)x
                          ^
src/config.c:90:20: note: in expansion of macro ‘CASTTOPTR’
  change_oversample(CASTTOPTR(void,mused.oversample), 0, 0);
                    ^
cc1: all warnings being treated as errors
Makefile:151: recipe for target 'objs.release/config.o' failed
make[3]: *** [objs.release/config.o] Error 1
make[3]: Leaving directory '/data/klystrack-0.20171212/klystrack'
Makefile:128: recipe for target 'build' failed
make[2]: *** [build] Error 2
make[2]: Leaving directory '/data/klystrack-0.20171212/klystrack'
dh_auto_build: make -j1 CFG=release returned exit code 2
debian/rules:15: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/data/klystrack-0.20171212'
debian/rules:12: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by alexmyczko** [comment]
There is a few more architectures that did not build (red): https://buildd.debian.org/status/package.php?p=klystrack&suite=unstable

**Comment by kometbomb** [comment]
The method I use there is terrible but I guess it's unavoidable since I'm not rewriting this in the near future. :) I assume the pointers something like 48 bits wide or so. Need to check if there's a safe way to force it to 64 bits or so.

**Comment by darkhog** [comment]
Maybe this has something to do with this?

    cc1: all warnings being treated as errors

Try turning that option off and see if it builds then.

**Comment by kometbomb** [comment]
That indeed is what stops the build but it's never good to just ignore
warnings. It would probably work right now but what if the pointer type was
larger than the provided 64 bits? Better to fix the warning.

2018-01-03 21:50 GMT+02:00 darkhog <notifications@github.com>:

**Comment by kometbomb** [comment]
I am not able to test all platforms but I just committed a fix here: kometbomb/klystron@ba8e768ad6bd8bec0fb7c0f3b01cb60f02c70013

This ensures the cast is done with a type whose width equals that of a pointer type. Can the build process above be tested with the branch referenced above?

**Comment by alexmyczko** [comment]
I can test it on 32bit ppc... will report back results here.

**Comment by alexmyczko** [comment]
works

**Comment by kometbomb** [comment]
Thanks a lot for testing! I'll merge the klystron PR.
