### ISSUE TITLE
[Feature request] Most recently opened file list

### ISSUE THREAD

**Issue by darkhog** [kometbomb/klystrack#223]
It would be useful to have it. Currently I have to open the list, navigate to the folder I store my songs at (I have it favorited, but still), then open the song. Even if it was a song I've chipped at (pun intended) in previous session. Some sort of "recent files" button, perhaps next to favorite tab/button with a list that would store 10-20 most recently opened songs would be great.

**Comment by kometbomb** [comment]
Yeah this seems a good feature.

**Comment by kometbomb** [comment]
This feature is added in 307d0386968a9515f3890e2a5e1552e2369fedc1.

![image](https://user-images.githubusercontent.com/1084137/34652545-7423dc20-f3e8-11e7-88bc-2d523f2aff59.png)
