### ISSUE TITLE
Clarifying license

### ISSUE THREAD

**Issue by trebmuh** [kometbomb/klystrack#227]
_(I've read https://github.com/kometbomb/klystrack/issues/214 )_

Could you please clarify the license(s) used with adding a LICENSE file in the root directory?

Thanks for Klystrack, a lot of fun when using it :)

**Comment by kometbomb** [comment]
Moved LICENSE from doc/ to /. 

d004fcfee48dd5e366a3db2f0078e8db4d71b54f
