### ISSUE TITLE
Using Increase/Decrease L/R button in Tap section crashes Klystrack

### ISSUE THREAD

**Issue by DeltaRazero** [kometbomb/klystrack#235]
This occurs at anytime, not just at startup. Using Windows 7 Professional 64bit

Procedure:
Open klystrack
Goto FX page
Click on this button in whatever direction you want
![image](https://user-images.githubusercontent.com/26445643/37982446-dfcfd9ce-31f0-11e8-87c9-e0d58864be98.png)
Program crashes

**Comment by DeltaRazero** [comment]
I'd like to note that just dragging the dots in Pan view mode works fine

**Comment by kometbomb** [comment]
OK, sorry for taking a bit to get back to you but here's the status: I could reproduce this under the release build but of course the debug build doesn't crash.
