### ISSUE TITLE
Doesn't  make any noise

### ISSUE THREAD

**Issue by pezz** [kometbomb/klystrack#248]
Hi,

I installed this tonight on Windows 10, loaded up a demo tune, the song plays but there's no audio output.

In fact, none of the demo tunes work.

**Comment by kometbomb** [comment]
Do you have something uncommon with your audio setup? Multiple audio devices?

**Comment by pezz** [comment]
No, there's only one audio device.

Sorry for not being very helpful, I'm not sure what other info I can give you. :(

**Comment by muchitto** [comment]
Same for me. Installed the newest version today on windows 10 and the volume bars are moving as if there is sound, but nothing is really coming out of the speakers.

**Comment by kometbomb** [comment]
I think the cause is the use of the latest SDL version (the only thing that has changed in relation to direct audio things). I most likely need to add some audio conversion on the klystron side to support this change.

https://www.doomworld.com/forum/topic/97402-important-for-devs-sdl2-206s-audio-breakage-in-windows/

**Comment by kometbomb** [comment]
Can one of you check if this fixes it? Just replace the klystrack.exe with this one, it should handle the audio format conversion.

https://www.dropbox.com/s/rnrlvsn1ddl69k2/klystrack.zip?dl=0

**Comment by pezz** [comment]
Sorry mate, still no output with this version.

**Comment by kometbomb** [comment]
This one should set the audio driver to "directsound". If this works it's at least a quick fix until I find time to rewrite the (messy) audio buffer routine.

https://www.dropbox.com/s/7yv12vnc4vq818l/klystrack-directsound.zip?dl=0

**Comment by pezz** [comment]
Sorry for forgetting to respond, the newest one you posted above works great!
