### ISSUE TITLE
Display flashing when resizing window

### ISSUE THREAD

**Issue by marespiaut** [kometbomb/klystrack#269]
Hello,

I've compiled commit 4db79648b14f5ed06c4324fc230bfdd9e90abd61 on my Arch Linux machine, using the i3wm.

The window starts to flash endlessly at very high speed if I resize it, alternating from full black screen, to normal screen.

**Comment by fpesari** [comment]
Try Menu > Prefs > Disable rendering to texture

does it still happen?

**Comment by marespiaut** [comment]
Hello,

I've just compiled commit bb53759 and the option “Disable rendering to texture” does fix the issue!

Thank you very much!

**Comment by kometbomb** [comment]
:+1:  The config option has been there for a while but I made the setting disabled by default.
