### ISSUE TITLE
Rendering to texture causes flashing

### ISSUE THREAD

**Issue by fpesari** [kometbomb/klystrack#278]
On my system (Debian testing, graphics card: Intel HD 5200), rendering to a texture causes klystrack to flash at a high rate, making it unusable (and I think it could cause epileptic attacks!).

Until this bug is fixed, I suggest RTT is disabled by default, because it can turn off potential users after they launch the program for the first time.

Edit: This tracker is awesome, by the way! :+1:

**Comment by kometbomb** [comment]
That is a very good point about epilepsy, I think this needs to be disabled by default on Linux.

**Comment by kometbomb** [comment]
#279 should fix this. It can still be enabled by the user but it's off by default.
