### ISSUE TITLE
Double free crash when exporting to wav

### ISSUE THREAD

**Issue by fgaz** [kometbomb/klystrack#287]
OS: Linux
Version: current master

Step to reproduce: try to export any song. It will often crash after exporting a single pattern and more rarely after exporting the whole song.

```
free(): double free detected in tcache 2
Aborted (core dumped)
```

**Comment by kometbomb** [comment]
Fixed by #289

**Comment by fgaz** [comment]
Can confirm, works great!

Any chance of a new release with the fix?

**Comment by kometbomb** [comment]
I'll make a release as soon as I get my build setup running (had to switch
computers a while ago etc.)!

la 21. maalisk. 2020 klo 14.53 Francesco Gazzetta (notifications@github.com)
kirjoitti:
