### ISSUE TITLE
Issue building klystrack on Linux

### ISSUE THREAD

**Issue by distek** [kometbomb/klystrack#295]
Hello,

I found your repo and wanted to give it a try! However, during the build I received this:
```
/usr/bin/ld: objs.debug/command.o:/home/distek/git-clones/klystrack/klystron/src/gui/menu.h:36: multiple definition of `menu_t'; objs.debug/action.o:/home/distek/git-clones/klystrack/klystron/src/gui/menu.h:36: first defined here
```
for all of the `.o` files during linking.

I was able to resolve this by changing the `menu_t` definition in `menu.h` to the following:
```
struct menu_t
{
	int flags;
	const struct menu_t *parent;
	const char * text;
	const struct menu_t *submenu;
	void (*action)(void*, void*, void *);
	void *p1, *p2, *p3;
};
```
The only change being the removal of `menu_t` after the struct definition:
```
} menu_t;
```

I don't know if this would cause issues on other platforms, so I'm just opening this issue for now. If for no other reason than to help someone else using Linux to be able to build this successfully.

Thank you for what you do.

**Comment by fgaz** [comment]
fwiw, I'm on linux too and klystrack builds both with and without the patch

**Comment by rofl0r** [comment]
it's usually a bad idea to declare a global variable from a header that's included from multiple translation units. the right fix would be to declare only the struct type in the header with a reference to an external instance, which then lives in a single TU. but since @fgaz reports that klystrack builds with the patch, the variable menu_t is probably not even used.

**Comment by kometbomb** [comment]
I think it's safe to say that is just a typo and missing the typedef
keyword.

to 24. syysk. 2020 klo 13.44 rofl0r (notifications@github.com) kirjoitti:

**Comment by rofl0r** [comment]
> I think it's safe to say that is just a typo and missing the typedef keyword.

in this case it would make sense that @distek files a PR with his patch.

**Comment by kometbomb** [comment]
Agreed.

to 24. syysk. 2020 klo 22.10 rofl0r (notifications@github.com) kirjoitti:

**Comment by kometbomb** [comment]
Merged. Thanks!
